### ISSUE TITLE
FIX SEO metadata.

### ISSUE THREAD

**Issue by itfobos** [itfobos/hugo-yml-corrector#3]
1. Structure should be like:

```
      - label: "Metadata"
        name: "metadata"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Meta description", name: "seodescription", widget: "string", required: false}
          - {label: "Page title", name: "pagetitle", widget: "string", required: false}
          - {label: "No index the page", name: "noindexpage", widget: "boolean", default: false}
          - {label: "Canonical URL", name: "canonical", widget: "string", required: false}
```

2. Fix image link.
